Fix unwanted nametags paint tooltip
SevenTV/Extension pull request #414
Opened 2023-03-29 01:17 UTC by MatinAniss

Added check that removes the nametag paint name tooltip if setting "vanity.nametag_paints" (Nametag Paints) is undefined (disabled).

Fixes issue: #410

2023-04-07 21:32 UTC, Melonify requested changes
Not sure this is the right way to do this, I think it would be preferable to instead not set `paint` when the setting is disabled.

2023-04-17 22:46 UTC, AnatoleAM requested changes
`paint` should simply not be set when the option is disabled, rather than adding this extra check in the template.

2023-04-18 01:31 UTC, MatinAniss commented
ah, that is what you meant. I changed how name tags paints should be disabled overall which removes the old method which was commented to be replaced. This way the nametag paint and tooltip are disabled without extra checks like I did. :)

2023-04-19 18:42 UTC, AnatoleAM approved these changes

2023-04-19 18:49 UTC, merged