Reset to default setting feature
SevenTV/Extension pull request #758
Opened 2023-07-06 06:07 UTC by chipsTM

adds #576 

![image](https://github.com/SevenTV/Extension/assets/90581578/e8fadd1e-effe-4e37-b12e-c6f70f31f437)

taking suggestions on css formatting and handling custom components/ignores

2023-07-06 15:11 UTC, chipsTM commented
I was thinking that another property (`disableReset` ?) should be added to `SettingNode` interface so that a setting can be declared as non-resettable when one uses `declareConfig`. At least this way we can exclude custom types or types with non-primitive values?

2023-07-16 03:38 UTC, Melonify commented
The behavior of this isn't quite right. Ideally it should remove the setting from the stored table entirely, so that if a setting's default value changes for some reason it's as if the user had never changed the setting.

Allowing the post-reset state to be separate from the initial state adds to potential user confusion.

2023-07-22 03:55 UTC, AnatoleAM requested changes

2023-07-22 03:55 UTC, AnatoleAM commented on src/app/settings/SettingsNode.vue
> +	db.settings.delete(props.node.key);
Please handle errors with `catch()` on the promise

2023-07-22 05:49 UTC, AnatoleAM approved these changes
Thank you for the contribution :slightly_smiling_face:

2023-07-22 05:52 UTC, merged