feat(twitch)/add side nav module
SevenTV/Extension pull request #767
Opened 2023-07-09 02:39 UTC by chipsTM

Adds requested features: 
#464
#728

![image](https://github.com/SevenTV/Extension/assets/90581578/042658dd-41e6-4f9f-bf3a-3a98bb0ac2b5)

2023-08-21 01:28 UTC, AnatoleAM requested changes

2023-08-21 01:28 UTC, AnatoleAM commented on src/site/twitch.tv/modules/side-nav/SideNav.vue
Duplicate of [src/site/twitch.tv/modules/side-nav/FollowedSideNav.vue](https://github.com/SevenTV/Extension/pull/767/files#diff-4b5ccd2af3a7afb039e9fe78efa41f36c9bddf9bbcde11e553c5c6ce27da59ff)?

2023-08-21 15:24 UTC, chipsTM commented on src/site/twitch.tv/modules/side-nav/SideNav.vue
Good point, the current behavior is the same in the files. I broke it out in case there might be future extension. See line 39-40 of [src/site/twitch.tv/modules/side-nav/SideNavModule.vue](https://github.com/SevenTV/Extension/pull/767/files#diff-deb0e8326a7f176d81857b820c32c62b8bac0d8595834c6fe7bc955440a0fe4dR39-R40)

2024-01-24 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SevenTV/Extension?pullRequest=767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SevenTV/Extension?pullRequest=767) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SevenTV/Extension?pullRequest=767) it.</sub>

2024-01-25 02:42 UTC, Noctumsempra commented
Hello. Any news on this? Auto expand feature still not present :(

2024-02-17 02:52 UTC, TroyKomodo commented
Features against this repo wont be implemented, we are going to rewrite the extension on this [repo](https://github.com/SevenTV/SevenTV).

2024-02-17 02:52 UTC, closed without merging