separate action on clicking vod and live video player
SevenTV/Extension pull request #807
Opened 2023-07-31 14:41 UTC by iw2d-rn

issue : https://github.com/SevenTV/Extension/issues/762

https://github.com/SevenTV/Extension/pull/802 unfortunately closed previous one :sweat_smile:

2023-08-12 05:05 UTC, iw2d-rn commented on src/site/twitch.tv/modules/player/PlayerController.vue
> +				.children.props.children.props.children.props.children.props.children.props.content.type;
how can i write it better. i could not think of any thing :sweat_smile:

2023-08-21 01:35 UTC, AnatoleAM requested changes
Sorry, you're gonna have to find a better way to do this. This is not

2023-08-21 01:35 UTC, AnatoleAM commented on src/site/twitch.tv/modules/player/PlayerController.vue
> +			"//div[contains(@class, 'persistent-player')]//div[contains(@class, 'tw-channel-status-text-indicator')]/p",
It's unclear why use an extremely old web technology when better alternatives, such as `document.querySelector()`, exist.

2024-01-24 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SevenTV/Extension?pullRequest=807) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SevenTV/Extension?pullRequest=807) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SevenTV/Extension?pullRequest=807) it.</sub>

2024-02-17 02:52 UTC, TroyKomodo commented
Features against this repo wont be implemented, we are going to rewrite the extension on this [repo](https://github.com/SevenTV/SevenTV).

2024-02-17 02:52 UTC, closed without merging