feat(twitch): hide featured clips
SevenTV/Extension pull request #866
Opened 2023-09-06 17:36 UTC by uriiusero

Add an option to hide featured clips

2023-11-26 22:51 UTC, AnatoleAM requested changes

2023-11-26 22:51 UTC, AnatoleAM commented on src/site/twitch.tv/modules/hidden-elements/HiddenElementsModule.vue
> +
Layout classes are autogenerated every time twitch rebuilds its website and these would quickly become invalid

2024-01-24 21:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SevenTV/Extension?pullRequest=866) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SevenTV/Extension?pullRequest=866) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SevenTV/Extension?pullRequest=866) it.</sub>

2024-02-17 02:52 UTC, TroyKomodo commented
Features against this repo wont be implemented, we are going to rewrite the extension on this [repo](https://github.com/SevenTV/SevenTV).

2024-02-17 02:52 UTC, closed without merging