Fix delete message functionality
SevenTV/Extension pull request #937
Opened 2023-11-18 02:49 UTC by MatinAniss

Fixed the functionality of the delete message function to use Apollo instead of IRC, this conforms with how Twitch natively handles deleting messages. This will also fix issues where users are failing to delete messages seen in the image below.

Issue:
![image](https://github.com/SevenTV/Extension/assets/76515905/cd6b2e69-d804-426f-9041-3d7abdcdc3ce)

2023-11-19 22:01 UTC, Melonify requested changes

2023-11-19 22:01 UTC, Melonify commented on src/composable/chat/useChatModeration.ts
> +		const apollo = useApollo();
Looks good, just one thing the `useApollo` call should probably be moved outside of this function and into the parent scope, the same way the `useChatMessages` composable was previously preserved.

2023-11-19 22:02 UTC, Melonify commented
Looks good, just the one requested change is the only issue.

2023-11-20 18:09 UTC, Melonify approved these changes

2023-11-20 18:09 UTC, Melonify commented
LGTM :+1:

2023-11-25 21:45 UTC, AnatoleAM approved these changes

2023-11-25 21:47 UTC, merged