#959 | Added option to hide channel point balance button
SevenTV/Extension pull request #960
Opened 2023-12-05 22:31 UTC by goralight

https://github.com/SevenTV/Extension/issues/959 : Added an option to hide the channel point balance button, which is under the chat input.

Enabled:
![image](https://github.com/SevenTV/Extension/assets/5850319/d7c53ed7-9097-45c1-a9fc-b85bb2f68a47)

Disabled:
![image](https://github.com/SevenTV/Extension/assets/5850319/f8713456-ee16-4ec7-b73d-1132d8adaf60)

2023-12-09 21:03 UTC, pimothyxd requested changes

2023-12-11 11:34 UTC, goralight commented on src/site/twitch.tv/modules/hidden-elements/HiddenElementsModule.vue
> +
Good point, I'll do a push now, thank you :)

2024-01-24 21:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SevenTV/Extension?pullRequest=960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SevenTV/Extension?pullRequest=960) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: John<br/>:x: goralight<br/><hr/>**John** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SevenTV/Extension?pullRequest=960) it.</sub>

2024-02-17 02:57 UTC, merged

2024-02-17 12:32 UTC, TroyKomodo commented
I can't change it because it would require to rebase the PR but it's fine. The cla typically is made prior to any changes going in but it was added long after this project started. The new rewrite of this extension will be more strict about signatures but we plan to get rid of this implementation soon.